package com.lms.common.audit;

public enum AuditEventType {
    USER_REGISTERED,
    USER_LOGGED_IN,
    USER_LOGGED_OUT,
    PASSWORD_CHANGED,
    PASSWORD_RESET_REQUESTED,
    COURSE_CREATED,
    COURSE_PUBLISHED,
    COURSE_ARCHIVED,
    COURSE_ENROLLED,
    LESSON_COMPLETED,
    COURSE_COMPLETED,
    PAYMENT_INITIATED,
    PAYMENT_SUCCEEDED,
    PAYMENT_FAILED,
    PAYMENT_REFUNDED,
    SUBSCRIPTION_ACTIVATED,
    SUBSCRIPTION_CANCELLED,
    SUBSCRIPTION_EXPIRED
}